import { Space_Mono } from "next/font/google";
import "./globals.css";
import Footer from "@/components/footer";
import { Suspense } from "react";
import Loading from "./loading";

const spaceMono = Space_Mono({ subsets: ["latin"], weight: ["400", "700"] });

export const metadata = {
  title: "KSummarizer",
  description:
    "Generated by create next appEnhance your reading with KSH-summarizer, an open-source article summarizer that transforms lengthy articles into concise summaries using the powerful GPT-4.",
  other: {
    "twitter:image": "https://i.ibb.co/0f4HSvq/ksh.png",
    "twitter:card": "summary_image_large",
    "twitter:url": "https://projekt-KSH-summarizer.vercel.app/",
    "twitter:domain": "ksh.vercel.app",
    "twitter:title": "Projekt KSH-summarizer",
    "twitter:description":
      "Generated by create next appEnhance your reading with KSH-summarizer, an open-source article summarizer that transforms lengthy articles into concise summaries using the powerful GPT-4.",

    "og:url": "https://ksh.vercel.app/",
    "og:type": "website",
    "og:title": "Projekt KSH-summarizer",
    "og:description":
      "Generated by create next appEnhance your reading with KSH-summarizer, an open-source article summarizer that transforms lengthy articles into concise summaries using the powerful GPT-4.",
    "og:image": "https://i.ibb.co/0f4HSvq/ksh.png",
  },
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${spaceMono.className} bg-background justify-evenly min-h-screen flex flex-col`}
      >
        <Suspense fallback={<Loading />}>
          {children}
          <Footer />
        </Suspense>
      </body>
    </html>
  );
}
